apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "akhildwivedi763@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "lqse rxno sgpn ljpg"
type: Opaque

# Passw0rd@1234